apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
  namespace: tke
data:
  admin.crt: |
{{ .Values.adminCrt | indent 4 }}
  admin.key: |
{{ .Values.adminKey | indent 4 }}
  server.crt: |
{{ .Values.serverCrt | indent 4 }}
  server.key: |
{{ .Values.serverKey | indent 4 }}
  webhook.crt: |
{{ .Values.webhookCrt | indent 4 }}
  webhook.key: |
{{ .Values.webhookKey | indent 4 }}
  ca.crt: |
{{ .Values.caCrt | indent 4 }}
  ca.key: |
{{ .Values.caKey | indent 4 }}
  etcd-ca.crt: |
{{ .Values.etcdCaCrt | indent 4 }}
  etcd.crt: |
{{ .Values.etcdCrt | indent 4 }}
  etcd.key: |
{{ .Values.etcdKey | indent 4 }}
  front-proxy-ca.crt: |
{{ .Values.frontProxyCaCrt | indent 4 }}
  password.csv: {{ .Values.passwordCsv }}
  token.csv: {{ .Values.tokenCsv }}