---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-monitor-controller
  name: tke-monitor-controller
  namespace: tke
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: tke-monitor-controller
  template:
    metadata:
      labels:
        app: tke-monitor-controller
      annotations:
        tke.prometheus.io/scrape: "true"
        prometheus.io/scheme: https
    spec:
      containers:
        - name: tke-monitor-controller
          image: {{ .Image }}
          args:
            - -C=/app/conf/tke-monitor-controller.toml
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-monitor-controller-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9456
          livenessProbe:
            httpGet:
              port: 9456
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-monitor-controller-volume
          configMap:
            name: tke-monitor-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-monitor-controller
  namespace: tke
data:
  tke-monitor-controller.toml: |
    monitor_config = "/app/conf/tke-monitor-config.yaml"

    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.monitor]
      api_server = "https://tke-monitor-api"
      api_server_client_config = "/app/conf/tke-monitor-api-config.yaml"

{{- if .EnableBusiness }}
      [client.business]
      api_server = "https://tke-business-api"
      api_server_client_config = "/app/conf/tke-business-api-config.yaml"
{{- end }}

  tke-monitor-api-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-monitor-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

{{- if .EnableBusiness }}
  tke-business-api-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-business-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
{{- end }}

  tke-monitor-config.yaml: |
    apiVersion: monitor.config.tkestack.io/v1
    kind: MonitorConfiguration
    storage:
{{- if eq .StorageType "influxDB" }}
      influxDB:
        servers:
          - address: {{ .StorageAddress }}
            username: {{ .StorageUsername }}
            password: {{ .StoragePassword }}
            timeoutSeconds: 10
{{- end }}
{{- if eq .StorageType "es" }}
      elasticSearch:
        servers:
          - address: {{ .StorageAddress }}
            username: {{ .StorageUsername }}
            password: {{ .StoragePassword }}
{{- end }}
