/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	internalversion "tkestack.io/tke/api/client/clientset/internalversion/typed/notify/internalversion"
)

type FakeNotify struct {
	*testing.Fake
}

func (c *FakeNotify) Channels() internalversion.ChannelInterface {
	return &FakeChannels{c}
}

func (c *FakeNotify) ConfigMaps() internalversion.ConfigMapInterface {
	return &FakeConfigMaps{c}
}

func (c *FakeNotify) Messages() internalversion.MessageInterface {
	return &FakeMessages{c}
}

func (c *FakeNotify) MessageRequests(namespace string) internalversion.MessageRequestInterface {
	return &FakeMessageRequests{c, namespace}
}

func (c *FakeNotify) Receivers() internalversion.ReceiverInterface {
	return &FakeReceivers{c}
}

func (c *FakeNotify) ReceiverGroups() internalversion.ReceiverGroupInterface {
	return &FakeReceiverGroups{c}
}

func (c *FakeNotify) Templates(namespace string) internalversion.TemplateInterface {
	return &FakeTemplates{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNotify) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
