# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
  - "ResponseStarted"
rules:
  - level: None
    resources:
      - group: ""
        resources: ["*/status", "pods/log", "events"]
      - group: "abac.authorization.kubernetes.io"
        resources: ["*/status"]
      - group: "apps"
        resources: ["*/status"]
      - group: "authentication.k8s.io"
        resources: ["*/status"]
      - group: "authorization.k8s.io"
        resources: ["*/status"]
      - group: "autoscaling"
        resources: ["*/status"]
      - group: "batch"
        resources: ["*/status"]
      - group: "extensions"
        resources: ["*/status"]
      - group: "networking.k8s.io"
        resources: ["*/status"]
      - group: "node.k8s.io"
        resources: ["*/status"]
      - group: "policy"
        resources: ["*/status"]
      - group: "rbac.authorization.k8s.io"
        resources: ["*/status"]
      - group: "settings.k8s.io"
        resources: ["*/status"]
      - group: "apps.tkestack.io"
        resources: ["*/status"]
      - group: "extensions.tkestack.io"
        resources: ["*/status"]
      - group: "platform.tkestack.io"
        resources: ["*/status"]
      - group: "lbcf.tkestack.io"
        resources: ["*/status"]
      - group: "auth.tkestack.io"
        resources: ["*/status"]
      - group: "business.tkestack.io"
        resources: ["*/status"]
      - group: "monitor.tkestack.io"
        resources: ["*/status"]
      - group: "notify.tkestack.io"
        resources: ["*/status"]
      - group: "registry.tkestack.io"
        resources: ["*/status"]
  - level: None
    users:
      - "system:admin"
      - "system:apiserver"
      - "system:kube-controller-manager"
      - "system:kube-scheduler"
      - "system:serviceaccount:kube-system:alertmanager-main"
      - "system:serviceaccount:kube-system:attachdetach-controller"
      - "system:serviceaccount:kube-system:bootstrap-signer"
      - "system:serviceaccount:kube-system:certificate-controller"
      - "system:serviceaccount:kube-system:clusterrole-aggregation-controller"
      - "system:serviceaccount:kube-system:coredns"
      - "system:serviceaccount:kube-system:cronjob-controller"
      - "system:serviceaccount:kube-system:csi-controller-tencentcbsv1"
      - "system:serviceaccount:kube-system:csi-operator"
      - "system:serviceaccount:kube-system:daemon-set-controller"
      - "system:serviceaccount:kube-system:default"
      - "system:serviceaccount:kube-system:deployment-controller"
      - "system:serviceaccount:kube-system:disruption-controller"
      - "system:serviceaccount:kube-system:endpoint-controller"
      - "system:serviceaccount:kube-system:expand-controller"
      - "system:serviceaccount:kube-system:flannel"
      - "system:serviceaccount:kube-system:galaxy"
      - "system:serviceaccount:kube-system:galaxy-ipam"
      - "system:serviceaccount:kube-system:generic-garbage-collector"
      - "system:serviceaccount:kube-system:helm"
      - "system:serviceaccount:kube-system:horizontal-pod-autoscaler"
      - "system:serviceaccount:kube-system:job-controller"
      - "system:serviceaccount:kube-system:kube-proxy"
      - "system:serviceaccount:kube-system:kube-state-metrics"
      - "system:serviceaccount:kube-system:lbcf-controller"
      - "system:serviceaccount:kube-system:log-collector"
      - "system:serviceaccount:kube-system:namespace-controller"
      - "system:serviceaccount:kube-system:node-controller"
      - "system:serviceaccount:kube-system:persistent-volume-binder"
      - "system:serviceaccount:kube-system:pod-garbage-collector"
      - "system:serviceaccount:kube-system:prometheus-k8s"
      - "system:serviceaccount:kube-system:prometheus-operator"
      - "system:serviceaccount:kube-system:pv-protection-controller"
      - "system:serviceaccount:kube-system:pvc-protection-controller"
      - "system:serviceaccount:kube-system:replicaset-controller"
      - "system:serviceaccount:kube-system:replication-controller"
      - "system:serviceaccount:kube-system:resourcequota-controller"
      - "system:serviceaccount:kube-system:service-account-controller"
      - "system:serviceaccount:kube-system:service-controller"
      - "system:serviceaccount:kube-system:serviceaccount-controller"
      - "system:serviceaccount:kube-system:statefulset-controller"
      - "system:serviceaccount:kube-system:tapp-controller"
      - "system:serviceaccount:kube-system:token-cleaner"
      - "system:serviceaccount:kube-system:ttl-controller"

  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/api*" # Wildcard matching.
      - "/version"
  - level: RequestResponse
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
