apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: tke
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - env:
        - name: GODEGUB
          value: madvdontneed=1
        {{- if .Values.resources }}
        - name: GOMAXPROCS
          value: {{ .Values.resources.limits.cpu| quote }}
        {{- end }}
        name: influxdb
        image: {{ .Values.image }}
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 1
          periodSeconds: 10
      {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
      {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb
          subPath:
{{- if .Values.baremetalStorage }}
      nodeName: {{ .Values.nodeName }}
{{- end }}
      volumes:
      - name: data
{{- if .Values.baremetalStorage }}
        hostPath:
          path: /var/lib/influxdb
          type: DirectoryOrCreate
{{- end }}
{{- if .Values.cephRbd }}
        persistentVolumeClaim:
          claimName: {{ .Values.cephRbdPVCName }}
{{- end }}
{{- if .Values.nfs }}
        persistentVolumeClaim:
          claimName: {{ .Values.nfsPVCName }}
{{- end }}
{{- if .Values.cephRbd }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cephRbdPVCName }}
  namespace: tke
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  storageClassName: {{ .Values.cephRbdStorageClassName }}
{{- end }}
{{- if .Values.nfs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfsPVCName }}
  namespace: tke
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  storageClassName: {{ .Values.nfsStorageClassName }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: tke
spec:
  ports:
    - name: remote-write
      port: 8086
      targetPort: 8086
      protocol: TCP
      nodePort: 30086
  type: NodePort
  selector:
    app: influxdb