/*
 * Copyright 2019 THL A29 Limited, a Tencent company.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "tkestack.io/tke/api/auth/v1"
	scheme "tkestack.io/tke/api/client/clientset/versioned/scheme"
)

// APISigningKeysGetter has a method to return a APISigningKeyInterface.
// A group's client should implement this interface.
type APISigningKeysGetter interface {
	APISigningKeys() APISigningKeyInterface
}

// APISigningKeyInterface has methods to work with APISigningKey resources.
type APISigningKeyInterface interface {
	Create(*v1.APISigningKey) (*v1.APISigningKey, error)
	Update(*v1.APISigningKey) (*v1.APISigningKey, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.APISigningKey, error)
	List(opts metav1.ListOptions) (*v1.APISigningKeyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.APISigningKey, err error)
	APISigningKeyExpansion
}

// aPISigningKeys implements APISigningKeyInterface
type aPISigningKeys struct {
	client rest.Interface
}

// newAPISigningKeys returns a APISigningKeys
func newAPISigningKeys(c *AuthV1Client) *aPISigningKeys {
	return &aPISigningKeys{
		client: c.RESTClient(),
	}
}

// Get takes name of the aPISigningKey, and returns the corresponding aPISigningKey object, and an error if there is any.
func (c *aPISigningKeys) Get(name string, options metav1.GetOptions) (result *v1.APISigningKey, err error) {
	result = &v1.APISigningKey{}
	err = c.client.Get().
		Resource("apisigningkeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of APISigningKeys that match those selectors.
func (c *aPISigningKeys) List(opts metav1.ListOptions) (result *v1.APISigningKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.APISigningKeyList{}
	err = c.client.Get().
		Resource("apisigningkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aPISigningKeys.
func (c *aPISigningKeys) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("apisigningkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a aPISigningKey and creates it.  Returns the server's representation of the aPISigningKey, and an error, if there is any.
func (c *aPISigningKeys) Create(aPISigningKey *v1.APISigningKey) (result *v1.APISigningKey, err error) {
	result = &v1.APISigningKey{}
	err = c.client.Post().
		Resource("apisigningkeys").
		Body(aPISigningKey).
		Do().
		Into(result)
	return
}

// Update takes the representation of a aPISigningKey and updates it. Returns the server's representation of the aPISigningKey, and an error, if there is any.
func (c *aPISigningKeys) Update(aPISigningKey *v1.APISigningKey) (result *v1.APISigningKey, err error) {
	result = &v1.APISigningKey{}
	err = c.client.Put().
		Resource("apisigningkeys").
		Name(aPISigningKey.Name).
		Body(aPISigningKey).
		Do().
		Into(result)
	return
}

// Delete takes name of the aPISigningKey and deletes it. Returns an error if one occurs.
func (c *aPISigningKeys) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("apisigningkeys").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aPISigningKeys) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("apisigningkeys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched aPISigningKey.
func (c *aPISigningKeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.APISigningKey, err error) {
	result = &v1.APISigningKey{}
	err = c.client.Patch(pt).
		Resource("apisigningkeys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
