apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: tke
data:
  daemon.json: |
    {
      "experimental": true,
      "debug": false,
    {{- if .IsGPU }}
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "/usr/bin/nvidia-container-runtime"
        }
      },
    {{- end}}
      "insecure-registries": [
        {{ .InsecureRegistries }}
      ],
      "ip-forward": true,
      "ip-masq": false,
      "iptables": false,
      "ipv6": false,
      "live-restore": true,
      "log-driver": "json-file",
      "log-level": "warn",
      "log-opts": {
        "max-file": "10",
        "max-size": "100m"
      },
      "selinux-enabled": false
    }
  docker.service: |
    [Unit]
    Description=Docker Application Container Engine
    Documentation=https://docs.docker.com
    After=network-online.target firewalld.service
    Wants=network-online.target

    [Service]
    Type=notify
    EnvironmentFile=-/etc/sysconfig/docker
    ExecStart=/usr/bin/dockerd $DOCKER_EXTRA_ARGS
    ExecReload=/bin/kill -s HUP $MAINPID
    LimitNOFILE=1048576
    LimitNPROC=infinity
    LimitCORE=infinity
    TimeoutStartSec=0
    Delegate=yes
    KillMode=process
    Restart=always
    StartLimitBurst=3
    StartLimitInterval=60s

    [Install]
    WantedBy=multi-user.target