/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	auth "tkestack.io/tke/api/auth"
)

// FakeCustomPolicyBindings implements CustomPolicyBindingInterface
type FakeCustomPolicyBindings struct {
	Fake *FakeAuth
	ns   string
}

var custompolicybindingsResource = schema.GroupVersionResource{Group: "auth.tkestack.io", Version: "", Resource: "custompolicybindings"}

var custompolicybindingsKind = schema.GroupVersionKind{Group: "auth.tkestack.io", Version: "", Kind: "CustomPolicyBinding"}

// Get takes name of the customPolicyBinding, and returns the corresponding customPolicyBinding object, and an error if there is any.
func (c *FakeCustomPolicyBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *auth.CustomPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(custompolicybindingsResource, c.ns, name), &auth.CustomPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*auth.CustomPolicyBinding), err
}

// List takes label and field selectors, and returns the list of CustomPolicyBindings that match those selectors.
func (c *FakeCustomPolicyBindings) List(ctx context.Context, opts v1.ListOptions) (result *auth.CustomPolicyBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(custompolicybindingsResource, custompolicybindingsKind, c.ns, opts), &auth.CustomPolicyBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &auth.CustomPolicyBindingList{ListMeta: obj.(*auth.CustomPolicyBindingList).ListMeta}
	for _, item := range obj.(*auth.CustomPolicyBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customPolicyBindings.
func (c *FakeCustomPolicyBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(custompolicybindingsResource, c.ns, opts))

}

// Create takes the representation of a customPolicyBinding and creates it.  Returns the server's representation of the customPolicyBinding, and an error, if there is any.
func (c *FakeCustomPolicyBindings) Create(ctx context.Context, customPolicyBinding *auth.CustomPolicyBinding, opts v1.CreateOptions) (result *auth.CustomPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(custompolicybindingsResource, c.ns, customPolicyBinding), &auth.CustomPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*auth.CustomPolicyBinding), err
}

// Update takes the representation of a customPolicyBinding and updates it. Returns the server's representation of the customPolicyBinding, and an error, if there is any.
func (c *FakeCustomPolicyBindings) Update(ctx context.Context, customPolicyBinding *auth.CustomPolicyBinding, opts v1.UpdateOptions) (result *auth.CustomPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(custompolicybindingsResource, c.ns, customPolicyBinding), &auth.CustomPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*auth.CustomPolicyBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomPolicyBindings) UpdateStatus(ctx context.Context, customPolicyBinding *auth.CustomPolicyBinding, opts v1.UpdateOptions) (*auth.CustomPolicyBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(custompolicybindingsResource, "status", c.ns, customPolicyBinding), &auth.CustomPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*auth.CustomPolicyBinding), err
}

// Delete takes name of the customPolicyBinding and deletes it. Returns an error if one occurs.
func (c *FakeCustomPolicyBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(custompolicybindingsResource, c.ns, name), &auth.CustomPolicyBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomPolicyBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(custompolicybindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &auth.CustomPolicyBindingList{})
	return err
}

// Patch applies the patch and returns the patched customPolicyBinding.
func (c *FakeCustomPolicyBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *auth.CustomPolicyBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(custompolicybindingsResource, c.ns, name, pt, data, subresources...), &auth.CustomPolicyBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*auth.CustomPolicyBinding), err
}
