#! /usr/bin/env bash
set -eo pipefail

CephImage=$1
DataDirHostPath=$2
PoolReplicas=$3

eval "echo \"`cat /app/manifests/rook/storageclass.yaml`\"" > storageclass.yaml
kubectl apply -f storageclass.yaml

echo "====rook ready===="

