/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
	v1 "tkestack.io/tke/api/monitor/v1"
)

// FakeClusterOverviews implements ClusterOverviewInterface
type FakeClusterOverviews struct {
	Fake *FakeMonitorV1
}

var clusteroverviewsResource = schema.GroupVersionResource{Group: "monitor.tkestack.io", Version: "v1", Resource: "clusteroverviews"}

var clusteroverviewsKind = schema.GroupVersionKind{Group: "monitor.tkestack.io", Version: "v1", Kind: "ClusterOverview"}

// Create takes the representation of a clusterOverview and creates it.  Returns the server's representation of the clusterOverview, and an error, if there is any.
func (c *FakeClusterOverviews) Create(ctx context.Context, clusterOverview *v1.ClusterOverview, opts metav1.CreateOptions) (result *v1.ClusterOverview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusteroverviewsResource, clusterOverview), &v1.ClusterOverview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterOverview), err
}
