---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-application-controller
  name: tke-application-controller
  namespace: tke
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: tke-application-controller
  template:
    metadata:
      labels:
        app: tke-application-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
        - name: tke-application-controller
          image: {{ .Image }}
          args:
            - -C=/app/conf/tke-application-controller.toml
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-application-controller-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9464
          livenessProbe:
            httpGet:
              port: 9464
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-application-controller-volume
          configMap:
            name: tke-application-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-application-controller
  namespace: tke
data:
  tke-application-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-config.yaml"

      [client.application]
      api_server = "https://tke-application-api"
      api_server_client_config = "/app/conf/tke-application-config.yaml"

    [features]
      [features.repo]
        scheme = "https"
        domain_suffix = "{{ .RegistryDomainSuffix }}"
        admin = "{{ .RegistryAdminUsername }}"
        admin_password = "{{ .RegistryAdminPassword }}"
        cafile = "/app/certs/ca.crt"

  tke-platform-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-platform-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

  tke-application-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-application-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke
