---
kind: Service
apiVersion: v1
metadata:
  name: tke-mesh-api
  namespace: tke
  annotations:
    tke.prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    app: tke-mesh-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9467
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: tke-mesh-api
  name: tke-mesh-api
  namespace: tke
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: tke-mesh-api
  template:
    metadata:
      labels:
        app: tke-mesh-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - tke-mesh-api
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
        - name: tke-mesh-api
          image: {{ .Image }}
          args:
            - -C=/app/conf/tke-mesh-api.toml
{{- if .EnableAudit }}
            - --audit-policy-file=/app/conf/audit-policy.yaml
            - --audit-webhook-config-file=/app/conf/audit-api-client-config.yaml
{{- end }}
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
            - name: tke-mesh-api-volume
              mountPath: /app/conf
          ports:
            - containerPort: 9467
          readinessProbe:
            httpGet:
              port: 9467
              path: /healthz/ping
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 9467
              path: /healthz
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: certs-volume
          configMap:
            name: certs
        - name: tke-mesh-api-volume
          configMap:
            name: tke-mesh-api
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tke-mesh-api
  namespace: tke
data:
  tke-mesh-api.toml: |
    mesh_config = "/app/conf/tke-mesh-config.yaml"

    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [etcd]
    servers = [
      "https://etcd.kube-system:2379"
    ]
    cafile = "/app/certs/etcd-ca.crt"
    certfile = "/app/certs/etcd.crt"
    keyfile = "/app/certs/etcd.key"

    [generic]
    external_hostname = "tke-mesh-api"
    external_port = 443

    [authentication]
    token_auth_file = "/app/certs/token.csv"
    client_ca_file = "/app/certs/ca.crt"

      [authentication.oidc]
{{- if .EnableAuth }}
      client_id = "default"
      issuer_url = "https://tke-auth-api/oidc"
      external_issuer_url = "https://tke-auth-api/oidc"
      ca_file = "/app/certs/ca.crt"
      username_prefix ="-"
      username_claim = "name"
      groups_claim = "groups"
      tenantid_claim = "federated_claims"
{{- else }}
      client_id = {{ .OIDCClientID }}
      issuer_url = {{ .OIDCIssuerURL }}
  {{- if .UseOIDCCA }}
      ca_file = "/app/certs/oidc-ca.crt"
  {{- end}}
{{- end }}

      [authentication.requestheader]
      client_ca_file = "/app/certs/front-proxy-ca.crt"
      username_headers = "X-Remote-User"
      group_headers = "X-Remote-Group"
      extra_headers_prefix = "X-Remote-Extra-"

    [client]

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-config.yaml"

  tke-auth-webhook.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-auth-api/auth/authz
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
    - context:
        cluster: tke
        user: admin-cert
      name: tke

  tke-platform-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          certificate-authority: /app/certs/ca.crt
          server: https://tke-platform-api
    users:
      - name: admin-cert
        user:
          client-certificate: /app/certs/admin.crt
          client-key: /app/certs/admin.key
    current-context: tke
    contexts:
      - context:
          cluster: tke
          user: admin-cert
        name: tke

  tke-mesh-config.yaml: |
    apiVersion: mesh.config.tkestack.io/v1
    kind: MeshConfiguration
    region:
      name: local
    istio:
      supportedVersion:
        - 1.6.6
      gateway:
        defaultHttpPort: 80
    components:
      meshManager:
        address: http://mesh-manager:10072

{{- if .EnableAudit }}
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    omitStages:
    - "RequestReceived"
    - "ResponseStarted"
    rules:
    - level: None
      resources:
      - group: "mesh.tkestack.io"
        resources: ["configmaps", "*/status"]
    - level: RequestResponse
      verbs: ["create", "update", "patch", "delete", "deletecollection"]

  audit-api-client-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: tke
        cluster:
          insecure-skip-tls-verify: true
          server: https://tke-audit-api/apis/audit.tkestack.io/v1/events/sink/control-plane
    current-context: tke
    contexts:
      - context:
          cluster: tke
        name: tke

  {{- end }}
