#!/bin/bash

echo "post-cluster-ready is override by expansion~"

echo "==== prepare tcnp base resource ==="

cat << EOF | kubectl apply -f-
apiVersion: v1
kind: Namespace
metadata:
  name: demo
EOF


