---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: https
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    component: etcd
  type: ClusterIP
