/** 展示数据的形式配置 */
export const dataFormatConfig = {
  text: 'text',
  array: 'array',
  env: 'env',
  volume: 'volume',
  probe: 'probe',
  operator: 'operator',
  labels: 'labels',
  keyvalue: 'keyvalue',
  replicas: 'replicas',
  ip: 'ip',
  time: 'time',
  rules: 'rules',
  pods: 'pods',
  ports: 'ports',
  status: 'status',
  mapText: 'mapText',
  ingressType: 'ingressType',
  ingressRule: 'ingressRule',
  checker: 'checker',
  lbcfBGPort: 'lbcfBGPort',
  backendGroups: 'backendGroups',
  backendRecords: 'backendRecords',
  forceDeletePod: 'forceDeletePod',
  resourceLimit: 'resourceLimit'
};
