apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kmsConfigMapName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ceph-csi-rbd.name" . }}
    chart: {{ include "ceph-csi-rbd.chart" . }}
    component: {{ .Values.nodeplugin.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
{{ toJson .Values.encryptionKMSConfig | indent 4 -}}
