{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ceph-csi-rbd.name" . }}
    chart: {{ include "ceph-csi-rbd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  userID: {{ .Values.secret.userID }}
  userKey: {{ .Values.secret.userKey }}

  encryptionPassphrase: {{ .Values.secret.encryptionPassphrase }}
{{- end -}}
