/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	auth "tkestack.io/tke/api/auth"
)

// ProjectRoleLister helps list ProjectRoles.
type ProjectRoleLister interface {
	// List lists all ProjectRoles in the indexer.
	List(selector labels.Selector) (ret []*auth.ProjectRole, err error)
	// Get retrieves the ProjectRole from the index for a given name.
	Get(name string) (*auth.ProjectRole, error)
	ProjectRoleListerExpansion
}

// projectRoleLister implements the ProjectRoleLister interface.
type projectRoleLister struct {
	indexer cache.Indexer
}

// NewProjectRoleLister returns a new ProjectRoleLister.
func NewProjectRoleLister(indexer cache.Indexer) ProjectRoleLister {
	return &projectRoleLister{indexer: indexer}
}

// List lists all ProjectRoles in the indexer.
func (s *projectRoleLister) List(selector labels.Selector) (ret []*auth.ProjectRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*auth.ProjectRole))
	})
	return ret, err
}

// Get retrieves the ProjectRole from the index for a given name.
func (s *projectRoleLister) Get(name string) (*auth.ProjectRole, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(auth.Resource("projectrole"), name)
	}
	return obj.(*auth.ProjectRole), nil
}
