/*
 * Copyright 2019 THL A29 Limited, a Tencent company.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "tkestack.io/tke/api/client/clientset/versioned/typed/registry/v1"
)

type FakeRegistryV1 struct {
	*testing.Fake
}

func (c *FakeRegistryV1) Charts(namespace string) v1.ChartInterface {
	return &FakeCharts{c, namespace}
}

func (c *FakeRegistryV1) ChartGroups() v1.ChartGroupInterface {
	return &FakeChartGroups{c}
}

func (c *FakeRegistryV1) ConfigMaps() v1.ConfigMapInterface {
	return &FakeConfigMaps{c}
}

func (c *FakeRegistryV1) Namespaces() v1.NamespaceInterface {
	return &FakeNamespaces{c}
}

func (c *FakeRegistryV1) Repositories(namespace string) v1.RepositoryInterface {
	return &FakeRepositories{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRegistryV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
