/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package helmClient

// Insufficient storage
type HarborInsufficientStorageChartApiError struct {
	// The error message returned by the chart API
	Error_ string `json:"error"`
}
