/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package helmClient

// The object contains basic chart information
type HarborChartInfoEntry struct {
	// Name of chart
	Name string `json:"name"`
	// Total count of chart versions
	TotalVersions int32 `json:"total_versions"`
	// latest version of chart
	LatestVersion string `json:"latest_version,omitempty"`
	// The created time of chart
	Created string `json:"created"`
	// The created time of chart
	Updated string `json:"updated,omitempty"`
	// The icon path of chart
	Icon string `json:"icon,omitempty"`
	// The home website of chart
	Home string `json:"home,omitempty"`
	// Flag to indicate if the chart is deprecated
	Deprecated bool `json:"deprecated,omitempty"`
}
