apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: tke
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
spec:
  rules:
    - host: "registry.tke.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
    - host: "*.registry.tke.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
    - host: "tke-gateway"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tke-gateway
                port:
                  number: 80
  ingressClassName: nginx
