# disable selinux


# disable selinux
- name: disable selinux
  shell: if [ -f "/etc/selinux/config" ]; then \
           sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config; \
           setenforce 0 || echo "is disabled !!!" ; \
         fi
  when: inventory_hostname in groups['masters'] or inventory_hostname in groups['workers']
  tags: selinux_init

