# update centos kernal

# check kernal whether need update for es
- name: check kernal whether need update for es
  shell: if [ `echo {{ ansible_kernel }} | grep tlinux2 | wc -l` -eq 0 ]; then \
           if [ `echo {{ ansible_kernel }} | awk -F\- '{print $1}' | awk -F. '{print $1}'` -lt 3 ]; then \
             echo "true"; \
           else  \
             if [ `echo {{ ansible_kernel }} | awk -F\- '{print $1}' | awk -F. '{print $2}'` -lt 10 ]; then \
               echo "true"; \
             else \
               if [ `echo {{ ansible_kernel }} | awk -F\- '{print $1}' | awk -F. '{print $3}'` -eq 0 ]; then \
                 if [ `echo {{ ansible_kernel }} | awk -F\- '{print $NF}' | awk -F. '{print $1}'` -lt 1075 ]; then \
                   echo "true"; \
                 fi; \
               fi; \
             fi; \
           fi; \
         fi
  register: is_update_kernel
  when: ansible_distribution == 'CentOS'
  tags: update_kernel

# update kernel for es on centos7.x
- name: update kernel for es on centos7.x
  shell: yum clean all && yum --disablerepo=\* --enablerepo=offline-yum update kernel -y
  when: ansible_distribution == 'CentOS' and is_update_kernel.stdout == "true"
  tags: update_kernel

# reboot machine validate the kernel
- name: reboot machine validate the kernel
  shell: reboot -n now
  when: ansible_distribution == 'CentOS' and is_update_kernel.stdout == "true" and inventory_hostname not in groups['installer']
  tags: update_kernel
