apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tke-auth-api.fullname" . }}-certs
  labels:
    {{- include "tke-auth-api.labels" . | nindent 4 }}
data:
{{ ( include "tke-auth-api.gen-certs" . ) | indent 2 }}