/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "tkestack.io/tke/api/client/clientset/internalversion/scheme"
	registry "tkestack.io/tke/api/registry"
)

// ChartsGetter has a method to return a ChartInterface.
// A group's client should implement this interface.
type ChartsGetter interface {
	Charts(namespace string) ChartInterface
}

// ChartInterface has methods to work with Chart resources.
type ChartInterface interface {
	Create(ctx context.Context, chart *registry.Chart, opts v1.CreateOptions) (*registry.Chart, error)
	Update(ctx context.Context, chart *registry.Chart, opts v1.UpdateOptions) (*registry.Chart, error)
	UpdateStatus(ctx context.Context, chart *registry.Chart, opts v1.UpdateOptions) (*registry.Chart, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*registry.Chart, error)
	List(ctx context.Context, opts v1.ListOptions) (*registry.ChartList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *registry.Chart, err error)
	ChartExpansion
}

// charts implements ChartInterface
type charts struct {
	client rest.Interface
	ns     string
}

// newCharts returns a Charts
func newCharts(c *RegistryClient, namespace string) *charts {
	return &charts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the chart, and returns the corresponding chart object, and an error if there is any.
func (c *charts) Get(ctx context.Context, name string, options v1.GetOptions) (result *registry.Chart, err error) {
	result = &registry.Chart{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("charts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Charts that match those selectors.
func (c *charts) List(ctx context.Context, opts v1.ListOptions) (result *registry.ChartList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &registry.ChartList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("charts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested charts.
func (c *charts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("charts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a chart and creates it.  Returns the server's representation of the chart, and an error, if there is any.
func (c *charts) Create(ctx context.Context, chart *registry.Chart, opts v1.CreateOptions) (result *registry.Chart, err error) {
	result = &registry.Chart{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("charts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chart).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a chart and updates it. Returns the server's representation of the chart, and an error, if there is any.
func (c *charts) Update(ctx context.Context, chart *registry.Chart, opts v1.UpdateOptions) (result *registry.Chart, err error) {
	result = &registry.Chart{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("charts").
		Name(chart.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chart).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *charts) UpdateStatus(ctx context.Context, chart *registry.Chart, opts v1.UpdateOptions) (result *registry.Chart, err error) {
	result = &registry.Chart{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("charts").
		Name(chart.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(chart).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the chart and deletes it. Returns an error if one occurs.
func (c *charts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("charts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *charts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("charts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched chart.
func (c *charts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *registry.Chart, err error) {
	result = &registry.Chart{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("charts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
