/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	applicationinternalversion "tkestack.io/tke/api/application"
	authinternalversion "tkestack.io/tke/api/auth"
	authzinternalversion "tkestack.io/tke/api/authz"
	businessinternalversion "tkestack.io/tke/api/business"
	logagentinternalversion "tkestack.io/tke/api/logagent"
	meshinternalversion "tkestack.io/tke/api/mesh"
	monitorinternalversion "tkestack.io/tke/api/monitor"
	notifyinternalversion "tkestack.io/tke/api/notify"
	platforminternalversion "tkestack.io/tke/api/platform"
	registryinternalversion "tkestack.io/tke/api/registry"
)

var scheme = runtime.NewScheme()
var codecs = serializer.NewCodecFactory(scheme)

var localSchemeBuilder = runtime.SchemeBuilder{
	applicationinternalversion.AddToScheme,
	authinternalversion.AddToScheme,
	authzinternalversion.AddToScheme,
	businessinternalversion.AddToScheme,
	logagentinternalversion.AddToScheme,
	meshinternalversion.AddToScheme,
	monitorinternalversion.AddToScheme,
	notifyinternalversion.AddToScheme,
	platforminternalversion.AddToScheme,
	registryinternalversion.AddToScheme,
}

// AddToScheme adds all types of this clientset into the given scheme. This allows composition
// of clientsets, like in:
//
//   import (
//     "k8s.io/client-go/kubernetes"
//     clientsetscheme "k8s.io/client-go/kubernetes/scheme"
//     aggregatorclientsetscheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
//   )
//
//   kclientset, _ := kubernetes.NewForConfig(c)
//   _ = aggregatorclientsetscheme.AddToScheme(clientsetscheme.Scheme)
//
// After this, RawExtensions in Kubernetes types will serialize kube-aggregator types
// correctly.
var AddToScheme = localSchemeBuilder.AddToScheme

func init() {
	v1.AddToGroupVersion(scheme, schema.GroupVersion{Version: "v1"})
	utilruntime.Must(AddToScheme(scheme))
}
