// +build !ignore_autogenerated

/*
 * Copyright 2019 THL A29 Limited, a Tencent company.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	auth "tkestack.io/tke/api/auth"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIKey)(nil), (*auth.APIKey)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKey_To_auth_APIKey(a.(*APIKey), b.(*auth.APIKey), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKey)(nil), (*APIKey)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKey_To_v1_APIKey(a.(*auth.APIKey), b.(*APIKey), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIKeyList)(nil), (*auth.APIKeyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKeyList_To_auth_APIKeyList(a.(*APIKeyList), b.(*auth.APIKeyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKeyList)(nil), (*APIKeyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKeyList_To_v1_APIKeyList(a.(*auth.APIKeyList), b.(*APIKeyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIKeyReq)(nil), (*auth.APIKeyReq)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKeyReq_To_auth_APIKeyReq(a.(*APIKeyReq), b.(*auth.APIKeyReq), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKeyReq)(nil), (*APIKeyReq)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKeyReq_To_v1_APIKeyReq(a.(*auth.APIKeyReq), b.(*APIKeyReq), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIKeyReqPassword)(nil), (*auth.APIKeyReqPassword)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKeyReqPassword_To_auth_APIKeyReqPassword(a.(*APIKeyReqPassword), b.(*auth.APIKeyReqPassword), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKeyReqPassword)(nil), (*APIKeyReqPassword)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKeyReqPassword_To_v1_APIKeyReqPassword(a.(*auth.APIKeyReqPassword), b.(*APIKeyReqPassword), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIKeySpec)(nil), (*auth.APIKeySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKeySpec_To_auth_APIKeySpec(a.(*APIKeySpec), b.(*auth.APIKeySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKeySpec)(nil), (*APIKeySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKeySpec_To_v1_APIKeySpec(a.(*auth.APIKeySpec), b.(*APIKeySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIKeyStatus)(nil), (*auth.APIKeyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIKeyStatus_To_auth_APIKeyStatus(a.(*APIKeyStatus), b.(*auth.APIKeyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.APIKeyStatus)(nil), (*APIKeyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_APIKeyStatus_To_v1_APIKeyStatus(a.(*auth.APIKeyStatus), b.(*APIKeyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalIdentity)(nil), (*auth.LocalIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalIdentity_To_auth_LocalIdentity(a.(*LocalIdentity), b.(*auth.LocalIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.LocalIdentity)(nil), (*LocalIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_LocalIdentity_To_v1_LocalIdentity(a.(*auth.LocalIdentity), b.(*LocalIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalIdentityList)(nil), (*auth.LocalIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalIdentityList_To_auth_LocalIdentityList(a.(*LocalIdentityList), b.(*auth.LocalIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.LocalIdentityList)(nil), (*LocalIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_LocalIdentityList_To_v1_LocalIdentityList(a.(*auth.LocalIdentityList), b.(*LocalIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalIdentitySpec)(nil), (*auth.LocalIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec(a.(*LocalIdentitySpec), b.(*auth.LocalIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.LocalIdentitySpec)(nil), (*LocalIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec(a.(*auth.LocalIdentitySpec), b.(*LocalIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalIdentityStatus)(nil), (*auth.LocalIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus(a.(*LocalIdentityStatus), b.(*auth.LocalIdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*auth.LocalIdentityStatus)(nil), (*LocalIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus(a.(*auth.LocalIdentityStatus), b.(*LocalIdentityStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_APIKey_To_auth_APIKey(in *APIKey, out *auth.APIKey, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_APIKeySpec_To_auth_APIKeySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_APIKeyStatus_To_auth_APIKeyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_APIKey_To_auth_APIKey is an autogenerated conversion function.
func Convert_v1_APIKey_To_auth_APIKey(in *APIKey, out *auth.APIKey, s conversion.Scope) error {
	return autoConvert_v1_APIKey_To_auth_APIKey(in, out, s)
}

func autoConvert_auth_APIKey_To_v1_APIKey(in *auth.APIKey, out *APIKey, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_auth_APIKeySpec_To_v1_APIKeySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_auth_APIKeyStatus_To_v1_APIKeyStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_auth_APIKey_To_v1_APIKey is an autogenerated conversion function.
func Convert_auth_APIKey_To_v1_APIKey(in *auth.APIKey, out *APIKey, s conversion.Scope) error {
	return autoConvert_auth_APIKey_To_v1_APIKey(in, out, s)
}

func autoConvert_v1_APIKeyList_To_auth_APIKeyList(in *APIKeyList, out *auth.APIKeyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]auth.APIKey)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_APIKeyList_To_auth_APIKeyList is an autogenerated conversion function.
func Convert_v1_APIKeyList_To_auth_APIKeyList(in *APIKeyList, out *auth.APIKeyList, s conversion.Scope) error {
	return autoConvert_v1_APIKeyList_To_auth_APIKeyList(in, out, s)
}

func autoConvert_auth_APIKeyList_To_v1_APIKeyList(in *auth.APIKeyList, out *APIKeyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]APIKey)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_auth_APIKeyList_To_v1_APIKeyList is an autogenerated conversion function.
func Convert_auth_APIKeyList_To_v1_APIKeyList(in *auth.APIKeyList, out *APIKeyList, s conversion.Scope) error {
	return autoConvert_auth_APIKeyList_To_v1_APIKeyList(in, out, s)
}

func autoConvert_v1_APIKeyReq_To_auth_APIKeyReq(in *APIKeyReq, out *auth.APIKeyReq, s conversion.Scope) error {
	out.Expire = in.Expire
	out.Description = in.Description
	return nil
}

// Convert_v1_APIKeyReq_To_auth_APIKeyReq is an autogenerated conversion function.
func Convert_v1_APIKeyReq_To_auth_APIKeyReq(in *APIKeyReq, out *auth.APIKeyReq, s conversion.Scope) error {
	return autoConvert_v1_APIKeyReq_To_auth_APIKeyReq(in, out, s)
}

func autoConvert_auth_APIKeyReq_To_v1_APIKeyReq(in *auth.APIKeyReq, out *APIKeyReq, s conversion.Scope) error {
	out.Expire = in.Expire
	out.Description = in.Description
	return nil
}

// Convert_auth_APIKeyReq_To_v1_APIKeyReq is an autogenerated conversion function.
func Convert_auth_APIKeyReq_To_v1_APIKeyReq(in *auth.APIKeyReq, out *APIKeyReq, s conversion.Scope) error {
	return autoConvert_auth_APIKeyReq_To_v1_APIKeyReq(in, out, s)
}

func autoConvert_v1_APIKeyReqPassword_To_auth_APIKeyReqPassword(in *APIKeyReqPassword, out *auth.APIKeyReqPassword, s conversion.Scope) error {
	out.TenantID = in.TenantID
	out.UserName = in.UserName
	out.Password = in.Password
	out.Description = in.Description
	out.Expire = in.Expire
	return nil
}

// Convert_v1_APIKeyReqPassword_To_auth_APIKeyReqPassword is an autogenerated conversion function.
func Convert_v1_APIKeyReqPassword_To_auth_APIKeyReqPassword(in *APIKeyReqPassword, out *auth.APIKeyReqPassword, s conversion.Scope) error {
	return autoConvert_v1_APIKeyReqPassword_To_auth_APIKeyReqPassword(in, out, s)
}

func autoConvert_auth_APIKeyReqPassword_To_v1_APIKeyReqPassword(in *auth.APIKeyReqPassword, out *APIKeyReqPassword, s conversion.Scope) error {
	out.TenantID = in.TenantID
	out.UserName = in.UserName
	out.Password = in.Password
	out.Description = in.Description
	out.Expire = in.Expire
	return nil
}

// Convert_auth_APIKeyReqPassword_To_v1_APIKeyReqPassword is an autogenerated conversion function.
func Convert_auth_APIKeyReqPassword_To_v1_APIKeyReqPassword(in *auth.APIKeyReqPassword, out *APIKeyReqPassword, s conversion.Scope) error {
	return autoConvert_auth_APIKeyReqPassword_To_v1_APIKeyReqPassword(in, out, s)
}

func autoConvert_v1_APIKeySpec_To_auth_APIKeySpec(in *APIKeySpec, out *auth.APIKeySpec, s conversion.Scope) error {
	out.APIkey = in.APIkey
	out.TenantID = in.TenantID
	out.Description = in.Description
	out.IssueAt = in.IssueAt
	out.ExpireAt = in.ExpireAt
	return nil
}

// Convert_v1_APIKeySpec_To_auth_APIKeySpec is an autogenerated conversion function.
func Convert_v1_APIKeySpec_To_auth_APIKeySpec(in *APIKeySpec, out *auth.APIKeySpec, s conversion.Scope) error {
	return autoConvert_v1_APIKeySpec_To_auth_APIKeySpec(in, out, s)
}

func autoConvert_auth_APIKeySpec_To_v1_APIKeySpec(in *auth.APIKeySpec, out *APIKeySpec, s conversion.Scope) error {
	out.APIkey = in.APIkey
	out.TenantID = in.TenantID
	out.Description = in.Description
	out.IssueAt = in.IssueAt
	out.ExpireAt = in.ExpireAt
	return nil
}

// Convert_auth_APIKeySpec_To_v1_APIKeySpec is an autogenerated conversion function.
func Convert_auth_APIKeySpec_To_v1_APIKeySpec(in *auth.APIKeySpec, out *APIKeySpec, s conversion.Scope) error {
	return autoConvert_auth_APIKeySpec_To_v1_APIKeySpec(in, out, s)
}

func autoConvert_v1_APIKeyStatus_To_auth_APIKeyStatus(in *APIKeyStatus, out *auth.APIKeyStatus, s conversion.Scope) error {
	out.Disabled = (*bool)(unsafe.Pointer(in.Disabled))
	out.Deleted = (*bool)(unsafe.Pointer(in.Deleted))
	return nil
}

// Convert_v1_APIKeyStatus_To_auth_APIKeyStatus is an autogenerated conversion function.
func Convert_v1_APIKeyStatus_To_auth_APIKeyStatus(in *APIKeyStatus, out *auth.APIKeyStatus, s conversion.Scope) error {
	return autoConvert_v1_APIKeyStatus_To_auth_APIKeyStatus(in, out, s)
}

func autoConvert_auth_APIKeyStatus_To_v1_APIKeyStatus(in *auth.APIKeyStatus, out *APIKeyStatus, s conversion.Scope) error {
	out.Disabled = (*bool)(unsafe.Pointer(in.Disabled))
	out.Deleted = (*bool)(unsafe.Pointer(in.Deleted))
	return nil
}

// Convert_auth_APIKeyStatus_To_v1_APIKeyStatus is an autogenerated conversion function.
func Convert_auth_APIKeyStatus_To_v1_APIKeyStatus(in *auth.APIKeyStatus, out *APIKeyStatus, s conversion.Scope) error {
	return autoConvert_auth_APIKeyStatus_To_v1_APIKeyStatus(in, out, s)
}

func autoConvert_v1_LocalIdentity_To_auth_LocalIdentity(in *LocalIdentity, out *auth.LocalIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_LocalIdentity_To_auth_LocalIdentity is an autogenerated conversion function.
func Convert_v1_LocalIdentity_To_auth_LocalIdentity(in *LocalIdentity, out *auth.LocalIdentity, s conversion.Scope) error {
	return autoConvert_v1_LocalIdentity_To_auth_LocalIdentity(in, out, s)
}

func autoConvert_auth_LocalIdentity_To_v1_LocalIdentity(in *auth.LocalIdentity, out *LocalIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_auth_LocalIdentity_To_v1_LocalIdentity is an autogenerated conversion function.
func Convert_auth_LocalIdentity_To_v1_LocalIdentity(in *auth.LocalIdentity, out *LocalIdentity, s conversion.Scope) error {
	return autoConvert_auth_LocalIdentity_To_v1_LocalIdentity(in, out, s)
}

func autoConvert_v1_LocalIdentityList_To_auth_LocalIdentityList(in *LocalIdentityList, out *auth.LocalIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]auth.LocalIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_LocalIdentityList_To_auth_LocalIdentityList is an autogenerated conversion function.
func Convert_v1_LocalIdentityList_To_auth_LocalIdentityList(in *LocalIdentityList, out *auth.LocalIdentityList, s conversion.Scope) error {
	return autoConvert_v1_LocalIdentityList_To_auth_LocalIdentityList(in, out, s)
}

func autoConvert_auth_LocalIdentityList_To_v1_LocalIdentityList(in *auth.LocalIdentityList, out *LocalIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LocalIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_auth_LocalIdentityList_To_v1_LocalIdentityList is an autogenerated conversion function.
func Convert_auth_LocalIdentityList_To_v1_LocalIdentityList(in *auth.LocalIdentityList, out *LocalIdentityList, s conversion.Scope) error {
	return autoConvert_auth_LocalIdentityList_To_v1_LocalIdentityList(in, out, s)
}

func autoConvert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec(in *LocalIdentitySpec, out *auth.LocalIdentitySpec, s conversion.Scope) error {
	out.UserName = in.UserName
	out.DisplayName = in.DisplayName
	out.Email = in.Email
	out.PhoneNumber = in.PhoneNumber
	out.HashedPassword = in.HashedPassword
	out.OriginalPassword = in.OriginalPassword
	out.TenantID = in.TenantID
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]string)(unsafe.Pointer(&in.Extra))
	return nil
}

// Convert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec is an autogenerated conversion function.
func Convert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec(in *LocalIdentitySpec, out *auth.LocalIdentitySpec, s conversion.Scope) error {
	return autoConvert_v1_LocalIdentitySpec_To_auth_LocalIdentitySpec(in, out, s)
}

func autoConvert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec(in *auth.LocalIdentitySpec, out *LocalIdentitySpec, s conversion.Scope) error {
	out.UserName = in.UserName
	out.DisplayName = in.DisplayName
	out.Email = in.Email
	out.PhoneNumber = in.PhoneNumber
	out.HashedPassword = in.HashedPassword
	out.OriginalPassword = in.OriginalPassword
	out.TenantID = in.TenantID
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]string)(unsafe.Pointer(&in.Extra))
	return nil
}

// Convert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec is an autogenerated conversion function.
func Convert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec(in *auth.LocalIdentitySpec, out *LocalIdentitySpec, s conversion.Scope) error {
	return autoConvert_auth_LocalIdentitySpec_To_v1_LocalIdentitySpec(in, out, s)
}

func autoConvert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus(in *LocalIdentityStatus, out *auth.LocalIdentityStatus, s conversion.Scope) error {
	out.Locked = in.Locked
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus is an autogenerated conversion function.
func Convert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus(in *LocalIdentityStatus, out *auth.LocalIdentityStatus, s conversion.Scope) error {
	return autoConvert_v1_LocalIdentityStatus_To_auth_LocalIdentityStatus(in, out, s)
}

func autoConvert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus(in *auth.LocalIdentityStatus, out *LocalIdentityStatus, s conversion.Scope) error {
	out.Locked = in.Locked
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus is an autogenerated conversion function.
func Convert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus(in *auth.LocalIdentityStatus, out *LocalIdentityStatus, s conversion.Scope) error {
	return autoConvert_auth_LocalIdentityStatus_To_v1_LocalIdentityStatus(in, out, s)
}
