/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	applicationv1 "tkestack.io/tke/api/application/v1"
)

// FakeUpgradeJobs implements UpgradeJobInterface
type FakeUpgradeJobs struct {
	Fake *FakeApplicationV1
	ns   string
}

var upgradejobsResource = schema.GroupVersionResource{Group: "application.tkestack.io", Version: "v1", Resource: "upgradejobs"}

var upgradejobsKind = schema.GroupVersionKind{Group: "application.tkestack.io", Version: "v1", Kind: "UpgradeJob"}

// Get takes name of the upgradeJob, and returns the corresponding upgradeJob object, and an error if there is any.
func (c *FakeUpgradeJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *applicationv1.UpgradeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(upgradejobsResource, c.ns, name), &applicationv1.UpgradeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*applicationv1.UpgradeJob), err
}

// List takes label and field selectors, and returns the list of UpgradeJobs that match those selectors.
func (c *FakeUpgradeJobs) List(ctx context.Context, opts v1.ListOptions) (result *applicationv1.UpgradeJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(upgradejobsResource, upgradejobsKind, c.ns, opts), &applicationv1.UpgradeJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &applicationv1.UpgradeJobList{ListMeta: obj.(*applicationv1.UpgradeJobList).ListMeta}
	for _, item := range obj.(*applicationv1.UpgradeJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested upgradeJobs.
func (c *FakeUpgradeJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(upgradejobsResource, c.ns, opts))

}

// Create takes the representation of a upgradeJob and creates it.  Returns the server's representation of the upgradeJob, and an error, if there is any.
func (c *FakeUpgradeJobs) Create(ctx context.Context, upgradeJob *applicationv1.UpgradeJob, opts v1.CreateOptions) (result *applicationv1.UpgradeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(upgradejobsResource, c.ns, upgradeJob), &applicationv1.UpgradeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*applicationv1.UpgradeJob), err
}

// Update takes the representation of a upgradeJob and updates it. Returns the server's representation of the upgradeJob, and an error, if there is any.
func (c *FakeUpgradeJobs) Update(ctx context.Context, upgradeJob *applicationv1.UpgradeJob, opts v1.UpdateOptions) (result *applicationv1.UpgradeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(upgradejobsResource, c.ns, upgradeJob), &applicationv1.UpgradeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*applicationv1.UpgradeJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUpgradeJobs) UpdateStatus(ctx context.Context, upgradeJob *applicationv1.UpgradeJob, opts v1.UpdateOptions) (*applicationv1.UpgradeJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(upgradejobsResource, "status", c.ns, upgradeJob), &applicationv1.UpgradeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*applicationv1.UpgradeJob), err
}

// Delete takes name of the upgradeJob and deletes it. Returns an error if one occurs.
func (c *FakeUpgradeJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(upgradejobsResource, c.ns, name), &applicationv1.UpgradeJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpgradeJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(upgradejobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &applicationv1.UpgradeJobList{})
	return err
}

// Patch applies the patch and returns the patched upgradeJob.
func (c *FakeUpgradeJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *applicationv1.UpgradeJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(upgradejobsResource, c.ns, name, pt, data, subresources...), &applicationv1.UpgradeJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*applicationv1.UpgradeJob), err
}
