/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type HarborProjectReq struct {
	// The name of the project.
	ProjectName string `json:"project_name,omitempty"`
	// deprecated, reserved for project creation in replication
	Public bool `json:"public,omitempty"`
	Metadata *HarborProjectMetadata `json:"metadata,omitempty"`
	CveAllowlist *HarborCveAllowlist `json:"cve_allowlist,omitempty"`
	// The storage quota of the project.
	StorageLimit int64 `json:"storage_limit,omitempty"`
	// The ID of referenced registry when creating the proxy cache project
	RegistryId int64 `json:"registry_id,omitempty"`
}
