/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type HarborIcon struct {
	// The content type of the icon
	ContentType string `json:"content-type,omitempty"`
	// The base64 encoded content of the icon
	Content string `json:"content,omitempty"`
}
