name: build-web

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: |
          make web
          make asset

      - name: Commit web
        run: |
          git config --global user.name 'QianChenglong'
          git config --global user.email 'qian_cheng_long@163.com'
          git commit -am 'ci: build web'
          git push