name: unit test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  test:
    name: unit test
    runs-on: self-hosted
    steps:
      - name: unit test
        run: |
          ginkgo -r -nodes=5 -v pkg
