---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: csi-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: csi-operator
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-operator
  namespace: kube-system
  labels:
    app: csi-operator-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-operator-controller
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kube-system
      labels:
        app: csi-operator-controller
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      serviceAccount: csi-operator
      containers:
        - name: csi-operator
          image: {{ .CSIOperatorImage }}
          args:
              - '--leader-election=true'
              - '--kubelet-root-dir=/var/lib/kubelet'
              - '--registry-domain={{ .RegistryDomain }}'
              - '--logtostderr=true'
              - '--v=5'
          resources:
            requests:
              cpu: "200m"
              memory: 256Mi
      priorityClassName: system-cluster-critical
